filter:
  excluded_paths:
    - 'vendor/*'
    - 'bin/*'
    - 'src/CL/Slack/Test/*'
    - 'src/CL/Slack/Tests/*'

before_commands:
  - 'sudo composer self-update'
  - 'composer install --no-interaction --no-scripts'

tools:
  php_code_sniffer:
    config:
      standard: PSR2
  php_cpd: true
  php_cs_fixer:
    config:
      level: all
  php_hhvm: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  external_code_coverage: true
