CL\Slack\Model\SimpleMessage:
    properties:
        ts:
            type: float
        type:
            type: string
        channel:
            type: CL\Slack\Model\SimpleChannel
        user:
            type: string
        username:
            type: string
        text:
            type: string
