CL\Slack\Payload\ChannelsHistoryPayloadResponse:
    properties:
        latest:
            type: float
        messages:
            type: array<CL\Slack\Model\SimpleMessage>
        hasMore:
            type: boolean
