CL\Slack\Payload\GroupsHistoryPayload:
    properties:
        channel:
            type: string
        oldest:
            type: float
        latest:
            type: float
        count:
            type: integer
        inclusive:
            type: boolean
